添加 Windows ARM64 目标支持

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -13,26 +13,29 @@ jobs:
     strategy:
       matrix:
         include:
-          - platform: android
-            os: ubuntu-latest
+#          - platform: android
+#            os: ubuntu-latest
           - platform: windows
             os: Windows-2022
             arch: amd64
-          - platform: linux
-            os: ubuntu-22.04
-            arch: amd64
-          - platform: macos
-            os: macos-15-intel
-            arch: amd64
-          - platform: macos
-            os: macos-latest
+          - platform: windows
+            os: Windows-2022
             arch: arm64
+#          - platform: linux
+#            os: ubuntu-22.04
+#            arch: amd64
+#          - platform: macos
+#            os: macos-15-intel
+#            arch: amd64
+#          - platform: macos
+#            os: macos-latest
+#            arch: arm64
           #          - platform: windows
           #            os: windows-11-arm
           #            arch: arm64
-          - platform: linux
-            os: ubuntu-24.04-arm
-            arch: arm64
+#          - platform: linux
+#            os: ubuntu-24.04-arm
+#            arch: arm64
 
     steps:
       - name: Setup rust
@@ -43,19 +46,23 @@ jobs:
           $cargoPath = "$env:USERPROFILE\.cargo\bin"
           Add-Content $env:GITHUB_PATH $cargoPath
 
+      - name: Setup Rust Target
+        if: matrix.platform == 'windows' && matrix.arch == 'arm64'
+        run: rustup target add aarch64-pc-windows-msvc
+
       - name: Checkout
         uses: actions/checkout@v4
         with:
           submodules: recursive
 
-      - name: Setup Android Signing
-        if: startsWith(matrix.platform,'android')
-        run: |
-          echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/keystore.jks
-          echo "${{ secrets.SERVICE_JSON }}" | base64 --decode > android/app/google-services.json
-          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/local.properties
-          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/local.properties
-          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/local.properties
+#      - name: Setup Android Signing
+#        if: startsWith(matrix.platform,'android')
+#        run: |
+#          echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/keystore.jks
+#          echo "${{ secrets.SERVICE_JSON }}" | base64 --decode > android/app/google-services.json
+#          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/local.properties
+#          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/local.properties
+#          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/local.properties
 
       - name: Setup Go
         uses: actions/setup-go@v5
@@ -128,39 +135,39 @@ jobs:
           
           mv "$temp" CHANGELOG.md
 
-      - name: Commit
-        if: ${{ env.IS_STABLE == 'true' }}
-        run: |
-          git add CHANGELOG.md
-          if ! git diff --cached --quiet; then
-            echo "Commit pushing"
-            git config --local user.email "chen08209@gmail.com"
-            git config --local user.name "chen08209"
-            git commit -m "Update changelog"
-            git push
-            if [ $? -eq 0 ]; then
-              echo "Push succeeded"
-            else
-              echo "Push failed"
-              exit 1
-            fi
-          fi
-
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#      - name: Commit
+#        if: ${{ env.IS_STABLE == 'true' }}
+#        run: |
+#          git add CHANGELOG.md
+#          if ! git diff --cached --quiet; then
+#            echo "Commit pushing"
+#            git config --local user.email "chen08209@gmail.com"
+#            git config --local user.name "chen08209"
+#            git commit -m "Update changelog"
+#            git push
+#            if [ $? -eq 0 ]; then
+#              echo "Push succeeded"
+#            else
+#              echo "Push failed"
+#              exit 1
+#            fi
+#          fi
+#
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   upload:
     permissions: write-all
     needs: [ build ]
     runs-on: ubuntu-latest
-    services:
-      telegram-bot-api:
-        image: aiogram/telegram-bot-api:latest
-        env:
-          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
-          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
-        ports:
-          - 8081:8081
+#    services:
+#      telegram-bot-api:
+#        image: aiogram/telegram-bot-api:latest
+#        env:
+#          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
+#          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
+#        ports:
+#          - 8081:8081
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -177,7 +184,7 @@ jobs:
       - name: Generate release.md
         run: |
           tags=($(git tag --merged HEAD --sort=-creatordate))
-          preTag=$(curl -s "https://api.github.com/repos/chen08209/FlClash/releases/latest" | \
+          preTag=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | \
           sed -nE 's/.*"tag_name": "([^"]+)".*/\1/p')
           
           [ -z "$preTag" ] && preTag=""
@@ -194,15 +201,15 @@ jobs:
             git log --no-merges --pretty=format:"%B" "$range" | \
             awk '!/Update changelog/ && NF {print "- " $0 "\n"}' >> "$out"
           done
-      - name: Push to telegram
-        env:
-          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
-          TAG: ${{ github.ref_name }}
-          RUN_ID: ${{ github.run_id }}
-        run: |
-          python -m pip install --upgrade pip
-          pip install requests
-          python release_telegram.py
+#      - name: Push to telegram
+#        env:
+#          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+#          TAG: ${{ github.ref_name }}
+#          RUN_ID: ${{ github.run_id }}
+#        run: |
+#          python -m pip install --upgrade pip
+#          pip install requests
+#          python release_telegram.py
 
       - name: Patch release.md
         run: |
@@ -224,25 +231,25 @@ jobs:
           files: ./dist/*
           body_path: './release.md'
 
-      - name: Create Fdroid Source Dir
-        if: ${{ env.IS_STABLE == 'true' }}
-        run: |
-          mkdir -p ./tmp
-          cp ./dist/*android-arm64-v8a* ./tmp/ || true
-          echo "Files copied successfully"
-
-      - name: Push to fdroid repo
-        if: ${{ env.IS_STABLE == 'true' }}
-        uses: cpina/github-action-push-to-another-repository@v1.7.2
-        env:
-          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
-        with:
-          source-directory: ./tmp/
-          destination-github-username: chen08209
-          destination-repository-name: FlClash-fdroid-repo
-          user-name: 'github-actions[bot]'
-          user-email: 'github-actions[bot]@users.noreply.github.com'
-          target-branch: main
-          commit-message: Update from ${{ github.ref_name }}
-          target-directory: /tmp/
+#      - name: Create Fdroid Source Dir
+#        if: ${{ env.IS_STABLE == 'true' }}
+#        run: |
+#          mkdir -p ./tmp
+#          cp ./dist/*android-arm64-v8a* ./tmp/ || true
+#          echo "Files copied successfully"
+#
+#      - name: Push to fdroid repo
+#        if: ${{ env.IS_STABLE == 'true' }}
+#        uses: cpina/github-action-push-to-another-repository@v1.7.2
+#        env:
+#          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
+#        with:
+#          source-directory: ./tmp/
+#          destination-github-username: chen08209
+#          destination-repository-name: FlClash-fdroid-repo
+#          user-name: 'github-actions[bot]'
+#          user-email: 'github-actions[bot]@users.noreply.github.com'
+#          target-branch: main
+#          commit-message: Update from ${{ github.ref_name }}
+#          target-directory: /tmp/
 
